### ISSUE TITLE
Display Bug of Auth Emulator in Android

### ISSUE THREAD

**Issue by CondorW** [firebase/firebase-tools-ui#1056]
**Describe the bug**
After implementing firebase and establishing a connection with the Emulator Suite, the Auth UI is visually bugged for unknown reasons. I dont know if my implementation is wrong or if this is a visual bug.

**To Reproduce**
```
class MainActivity : ComponentActivity() {
    private lateinit var signInLauncher: ActivityResultLauncher<Intent>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Initialize Firebase and connect to emulator
        FirebaseApp.initializeApp(this)
        Firebase.auth.useEmulator("10.0.2.2", 9099)
        AuthUI.getInstance().useEmulator("10.0.2.2", 9099)

        signInLauncher = registerForActivityResult(
            FirebaseAuthUIActivityResultContract()
        ) { result ->
            if (result.resultCode == Activity.RESULT_OK) {
                // Signed in successfully
                val user = Firebase.auth.currentUser
                Log.d("Auth", "User signed in: ${user?.uid}")
            } else {
                // Sign in failed
                Log.e("Auth", "Sign-in failed")
            }
        }

        setContent {
            ShiftyTheme {
                MainApp()
            }
        }
    }

    fun launchSignIn() {
        val providers = arrayListOf(
            AuthUI.IdpConfig.GoogleBuilder().build()
        )

        val signInIntent = AuthUI.getInstance()
            .createSignInIntentBuilder()
            .setAvailableProviders(providers)
            .setIsSmartLockEnabled(false)
            .build()

        signInLauncher.launch(signInIntent)
    }
}
```

```
@Composable
fun GoogleOAuthScreen(navController: NavController) {
    val context = LocalContext.current

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Button(
            onClick = {
                (context as? MainActivity)?.launchSignIn()
            }
        ) {
            Text("Sign in with Google")
        }
    }
}
```

**Expected behavior**
A visually working UI

**Screenshots**
Mobile Version Request:
![image](https://github.com/user-attachments/assets/62f3527e-c96b-493a-9921-2a497010b035)
![image](https://github.com/user-attachments/assets/e9b34440-5d68-47d1-a320-2b41a6c35906)
Desktop Version Request:
![image](https://github.com/user-attachments/assets/63baeb39-5819-4b0f-8321-8a3660af8733)

**Desktop (please complete the following information):**

- OS: [Win 10]

**Smartphone (please complete the following information):**

- Device: [Pixel 8 Emulator]
- OS: [API Level 35-ext13]
- Res: 1080x2400

**Additional context**

**Comment by yuchenshi** [comment]
I don't think you've done anything wrong and the Auth emulator certainly don't have this behavior since it's just a simple HTML page. I think this is probably more an artifact of how web views are displayed in the Android Emulator. Have you tried updating the base image, your display driver or a different device? I'm afraid that further questions may be better answered in Android development forums and I'm no expert here. Closing since it's not a thing we can fix within this repo

**Comment by CondorW** [comment]
Sounds plausible to me, however I tried with different Emulators (API 35 and API 34 [UpsideDownCake Android] and different resolutions and the problem persists. Nevertheless thank you for the fast answer I will open an issue in an Android related forum.
All the best!
