### ISSUE TITLE
Way to launch from within a package's dependencies?

### ISSUE THREAD

**Issue by mismith** [firebase/firebase-tools-ui#200]
This UI is just so incredibly helpful to my workflow—can't thank you enough for putting it together.

One thing I'm curious about is whether there's an easier/more convenient way to launch the UI from within existing firebase projects (e.g. one that doesn't require me to open a new terminal tab, and copy/paste/remember the snippet to launch).

For instance, here's what I personally picture the ideal setup looking like:

Some existing project folder, containing a `package.json` with:
```json
{
  "scripts": {
    "start": "app-cli-service start",
    "poststart": "firebase-tools-ui start"
  },
  "devDependencies": {
    "firebase-tools-ui": "^0.0.0"
  }
}
```

where the `firebase-tools-ui start` script essentially runs the equivalent of:
```bash
cd node_modules/firebase-tools-ui/
GCLOUD_PROJECT=<project-id> FIREBASE_EMULATOR_HUB=localhost:4400 npm start
```

This way, I can just add this repo as an npm package, and amend my scripts to launch the UI automatically (ideally without even having to configure the project-id).

I am totally willing to try and tackle this with a PR, but I just wanted to check that I'm not missing something (like maybe this is possible already somehow), or that this isn't fundamentally impossible for some reason or another.

Thoughts?

**Comment by samtstern** [comment]
Hey if you send me an email at samstern at google dot com I'll get you into our Alpha group which will include instructions to make things way easier.

**Comment by mismith** [comment]
Looks like there's a plan to improve this in the works, thanks @samtstern
