### ISSUE TITLE
Emulator GUI : Firestore : multi-decimal numbers

### ISSUE THREAD

**Issue by ultraGentle** [firebase/firebase-tools-ui#205]
Steps to reproduce:

1. In Firestore Emulator GUI 
2. Add a number field to a document
3. enter 1.2 -- so far so good 
4. enter 1.23 -- error: "must be a number"

Note: all x.y work, all x.yz fail

![screenshot](https://user-images.githubusercontent.com/41548755/81083778-fe54ee80-8ec2-11ea-8075-1be52b359641.png)

**Comment by yuchenshi** [comment]
Thanks for the detailed bug report. Would you mind taking a look, TJ?
