### ISSUE TITLE
SassError: Can't find stylesheet to import "@material/theme/mixins";

### ISSUE THREAD

**Issue by SreejithNS** [firebase/firebase-tools-ui#210]
> Failed to compile
> ./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
> SassError: Can't find stylesheet to import.
>    ╷
> 24 │ @.use "@material/theme/mixins";
>    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>   node_modules\@material\card\_variables.scss 24:1     @.forward
>   node_modules\@material\card\_index.scss 1:1          @.use
>   src\components\common\_material-overrides.scss 18:1  @.import
>   C:\Users\$USER$\firebase-tools-ui\src\index.scss 24:9                                           root stylesheet

npm start failed due **Compilation error**

**Comment by joed1rk** [comment]
I've noticed a similar compilation issue upon `npm start`
```
./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
SassError: Can't find stylesheet to import.
   ╷
20 │ @use '@material/notched-outline/_index' as notched-outline;
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/components/common/_material-overrides-inputs.scss 20:1  @import
  src/components/common/_material-overrides.scss 37:9         @import
  /Users/nkitzke/Workspace/firebase-tools-ui/src/index.scss 24:9       
```

**Comment by SreejithNS** [comment]
> I get a similar compilation issue upon `npm start`
> 
> ```
> ./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
> SassError: Can't find stylesheet to import.
>    ╷
> 20 │ @use '@material/notched-outline/_index' as notched-outline;
>    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>   src/components/common/_material-overrides-inputs.scss 20:1  @import
>   src/components/common/_material-overrides.scss 37:9         @import
>   /Users/nkitzke/Workspace/firebase-tools-ui/src/index.scss 24:9       
> ```

For now please change line 1 of ``.env`` file to  ```SASS_PATH=node_modules ```
This will work for Windows operating system

**Comment by yuchenshi** [comment]
Hey folks, please bear with us as we try to find a way that works across all OS. In the end, maybe we do need some detection for the current OS. We definitely want to make sure we get this right.

**Comment by gautamsingal** [comment]
@yuchenshi Can I be of some help here?

**Comment by yuchenshi** [comment]
@gautamsingal Yes, we welcome PRs to fix this. Just note that this is going to be tricky and needs to be manually tested on Windows and *nix. Attempts before include:

* #211 (`SASS_PATH=node_modules`), doesn't work on Linux
* #234 (`SASS_PATH=./node_modules;./src`), doesn't work on Windows

In the worst case, we may have to give up on `.env` and instead set env vars programmatically based on platform. https://www.npmjs.com/package/run-script-os looks promising, but we haven't got a chance to look at it yet.

**Comment by gautamsingal** [comment]
@yuchenshi Got it! Thanks for the clarification! Will start looking into the issue and the npm package mentioned.

**Comment by cristianberroeta** [comment]
Hi, I think that I've been able to fix this issue, by using the suggested npm package run-script-os, and setting the environment variable SASS_PATH inline in the npm scripts instead of in the .env file. I set that variable according to this docs: https://sass-lang.com/documentation/js-api#options where they say that on Windows you should use ";", and on other OS you should use ":".

I tested it on:
- macOS High Sierra 10.13.6 with Node 12.18.3,
- Windows 7 with Node 14.17.5 using the PowerShell,
- Ubuntu 16.04 with Node 14.17.5, using this dockerfile:
```dockerfile
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y build-essential curl git
RUN apt-get install -y openjdk-8-jre
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g --unsafe-perm firebase-tools@9.16.6
RUN git clone -b fix-windows-issue-with-npm-start --single-branch https://github.com/cristianberroeta/firebase-tools-ui.git
WORKDIR /firebase-tools-ui
RUN npm install
CMD sh

```

The start command I run was this in Mac and Ubuntu:
```sh
firebase emulators:exec --project sample --only database,firestore --import test-data 'npm start'
```

That command threw an error in Windows, but I removed the --only flag, and it worked:
```sh
firebase emulators:exec --project sample --import test-data 'npm start'
```

Please let me know if I'm doing something wrong, as I've just started contributing to this repository.

And please check again in your systems, specially in Windows, as my version of it is very old, and I had to do some weird hacks to even make Node.js work there.
