### ISSUE TITLE
Emulator UI should not connect to 0.0.0.0 for emulators

### ISSUE THREAD

**Issue by yuchenshi** [firebase/firebase-tools-ui#286]
In `firebase.json`, it is possible to specify `0.0.0.0` for `host` for each emulator. This tells an emulator to listen on all IPv4 interfaces (including `127.0.0.1`, the device's public network IP, etc.).

```json
{
  // ...
  "emulators": {
    "firestore": {"host": "0.0.0.0", "port": 8080},
  }
}
```

However, with this setup, the Emulator UI attempts to send requests `http://0.0.0.0:8080` to reach Firestore in the Firestore viewer. This is invalid since `0.0.0.0` is a non-routable address but some browsers / platforms (such as Chrome on Linux) special cases it to mean the same as `127.0.0.1`. On other browsers / platforms (such as Chrome on Windows), this fails with errors like `net::ERR_ADDRESS_INVALID`.

Instead, the Emulator UI should change it to `127.0.0.1` when constructing the URL. Similarly, the Emulator UI should connect to `::1` (IPv6 local) when `::` (IPv6 zero) is specified.

**Comment by gautamsingal** [comment]
@yuchenshi I would like to pick this up. As per my understanding, I think simply changing host to 127.0.0.1 in emulators would make it work. Please correct me if something else also needs to be done.

**Comment by yuchenshi** [comment]
@gautamsingal Of course! We welcome PRs addressing this. As noted in the last paragraph, please make sure to take care of both `0.0.0.0` and `::` for completeness. The best place to make the change is in `server.js`.

**Comment by gautamsingal** [comment]
@yuchenshi Thanks! Picking this up

**Comment by gautamsingal** [comment]
@yuchenshi I tried but unable to do. Can you please guide me in this?

**Comment by moneal** [comment]
I'm not sure if WSL2 is part of the official supported platforms but I was unable to get any host options working when they work fine elsewhere. Using a configuration like below should work, but the emulator UI and other front-end code can't connect. I would be happy to also help.

```
  "firestore": {
    "host": "127.0.0.1",
    "port": 8080
  },
```

**Comment by blastdan** [comment]
In server.js there are the lines

```js
Object.entries(emulators).forEach(([name, info]) => {
      json[name] = {
        hostAndPort: hostAndPort(info.host, info.port),
        ...info,
      }
    });
```

That host needs be checked for '0.0.0.0' and '::' If they are they should be changed to "localhost". All this logic is done using json so it makes it a bit more tricky.

**Comment by gautamsingal** [comment]
@blastdan Thanks for the feedback!

**Comment by moneal** [comment]
@blastdan Was it a issue with `node-sass` and `fsevents` by any chance? When setting up Windows environments I commonly need to force a install and rebuild.

```
npm i -f fsevents
npm rebuild node-sass
```

**Comment by yuchenshi** [comment]
@moneal @blastdan I think it's https://github.com/firebase/firebase-tools-ui/issues/210 -- a known issue. However, we still haven't found a great cross-platform solution and would appreciate any help there. Either way, let's move the discussion there.

**Comment by blastdan** [comment]
@yuchenshi Is there any way to track when a new release is made?

Thanks!

**Comment by yuchenshi** [comment]
@blastdan Yes! The Emulator UI releases with the Firebase CLI, so you can head to https://github.com/firebase/firebase-tools and click on the Watch dropdown menu and select "Releases only". GitHub will notify you if there is a new release to the Firebase CLI. This will be likely included in the next one or two Firebase CLI versions.

**Comment by yuchenshi** [comment]
FYI, this went out with Firebase CLI v8.6.0.

**Comment by evilrobot69** [comment]
I am still getting this error using an event listener on the realtime database emulator. See Chrome console errors:
GET http://0.0.0.0:9000/.lp?id=1&pw=cYijYEVq0A&ser=81095532&ns=joydominoes-default-rtdb net::ERR_ADDRESS_INVALID

firebase.json says:
"emulators": {
...
  "database": {
    "host": "0.0.0.0"
  }
...
}

firebase -V says
9.13.1

**Comment by c5n8** [comment]
this breaks https://github.com/firebase/firebase-tools/pull/1898
