### ISSUE TITLE
Firestore emulator UI does not display filtered values

### ISSUE THREAD

**Issue by wooliet** [firebase/firebase-tools-ui#335]
When applying a field filter to selected collection, the documents' value for the field is not displayed. It would be helpful to see the values alongside the document id (as you do in the normal firestore console environment).

---
### The filter

![image](https://user-images.githubusercontent.com/1421908/89305372-2c69dc00-d634-11ea-819d-b818aa833284.png)

### The collection display

![image](https://user-images.githubusercontent.com/1421908/89305412-38559e00-d634-11ea-9774-35dc3de08fd0.png)

**Comment by yuchenshi** [comment]
Fixed in #426.
