### ISSUE TITLE
Firestore Emulator saves time not in UTC but in the machines time zone

### ISSUE THREAD

**Issue by Yegorisa** [firebase/firebase-tools-ui#337]
#### firebase-tools:

8.7.0

#### Platform:

macOS

### Test case
Tried to set the timezone of emulator using `TZ=UTC` as referenced [here](https://github.com/firebase/firebase-tools/issues/2253) so that Firestore timestamps would be in UTC format.

#### Steps to reproduce
Run `TZ=UTC firebase emulators:start`
Open http://localhost:4000/firestore on Safari or Chrome
Add a collection and put document with the field of type timestamp

![image](https://user-images.githubusercontent.com/21309131/89699479-4e889480-d97b-11ea-9d7e-b0c4244f411f.png)

#### Expected behaviour
Time zone would be shown as UTC

#### Actual behavior
Firestore shows machines timezone (which is New Zealand as a shown in the screenshot)

**Comment by yuchenshi** [comment]
Hi! Firestore Timestamps are a fixed point in time, with no time zone information stored. What you see in the Emulator UI is merely converted for display purposes only to the browser time zone for you convenience. This display-only formatting is done in production Firebase Console as well.

If you query data using the SDKs, you will see Timestamps objects really don't have time zones and will be represented as UTC seconds and nanoseconds.

Hope that clear things out! For more information, check out the Firestore documentation: https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp
