### ISSUE TITLE
RTDB viewer has too much padding after emulator restart

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools-ui#341]
If you start the UI, open the database tab, CTRL-C the CLI, then open the same tab, everything gets pushed waaay down

![Screenshot from 2020-08-17 13-37-29](https://user-images.githubusercontent.com/969070/90431598-e75f9400-e08e-11ea-820e-a4d87b7bc67e.png)

**Comment by yuchenshi** [comment]
Is this still reproducible?
