### ISSUE TITLE
Firebase Emulator Suite Logs crashing

### ISSUE THREAD

**Issue by wdm954** [firebase/firebase-tools-ui#352]
### [REQUIRED] Environment info

**firebase-tools:** 8.10.0

**Platform:** macOS

### [REQUIRED] Test case

n/a

### [REQUIRED] Steps to reproduce

Open Logs tab in Firebase Emulator Suite.

Note: this only started to happen after I started using Firebase logger in Firebase functions.

### [REQUIRED] Expected behavior

not crashing

### [REQUIRED] Actual behavior

crashing with error:

    react-dom.production.min.js:209 TypeError: Cannot read property 'mode' of undefined
        at HighlightedJSON.tsx:174
        at Array.map (<anonymous>)
        at Hr (HighlightedJSON.tsx:95)
        at Qo (react-dom.production.min.js:153)
        at ms (react-dom.production.min.js:261)
        at cu (react-dom.production.min.js:246)
        at su (react-dom.production.min.js:246)
        at Zs (react-dom.production.min.js:239)
        at react-dom.production.min.js:123
        at e.unstable_runWithPriority (scheduler.production.min.js:19)

**Comment by samtstern** [comment]
@wdm954 transferring this issue over to the `firebase-tools-ui` repo.

**Comment by zprice-invsqr** [comment]
This error happens while a JSON string is being formatted. `line`s that end with `{}` or `{},` are incorrectly handled [here](https://github.com/firebase/firebase-tools-ui/blob/6c98653d671f6e73ad35907895b9fd3e8fb456fd/src/components/LogViewer/HighlightedJSON.tsx#L95), causing the next `line` to fail. The following logging from a cloud function reproduces the issue:
```
console.log(JSON.stringify({
    "this line": "is quite fine",
    "teh problematic boi": {},
    "innocent bystander": "(ಥ﹏ಥ)", // this line required for exception to be thrown
}));
```

**Comment by samhorlbeck** [comment]
Thanks for reaching out with the report!
