### ISSUE TITLE
Permission denied when importing JSON

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools-ui#361]
firebase-tools: 8.10.0

was fine in version 8.6

Platform: MacOS

![image](https://user-images.githubusercontent.com/216566/93599787-eb990d00-f9be-11ea-961f-cde5cf2e52fb.png)

**Comment by yuchenshi** [comment]
Looks like we did not set the header `Authorization: Bear owner` here, causing the import to be executed without admin privileges. https://github.com/firebase/firebase-tools-ui/blob/master/src/components/common/rest_api.ts#L72

Pull Requests are welcome.

**Comment by quantuminformation** [comment]
This pretty much broke my workflow for testing locally atm

**Comment by Villanuevand** [comment]
@yuchenshi , @quantuminformation 

Im trying to reproduce the error without results. 

```bash
firebase-tools@8.11.2
macOS Catalina V 10.15.7
```

@yuchenshi 
```js
protected async postFile(
    url: string,
    file: File,
    method: RequestMethod = 'POST'
  ) {
    const body = toFormData(file);

    const { accessToken } = await this.getToken();
    body.append('auth', accessToken);

    // headers are NOT allowed or it breaks the multipart/form-data payload
    const res = await fetch(url, { 
       method, body,
       headers: {
         Authorization: 'Bearer ' + accessToken,
         'Content-Type': 'multipart/form-data',
      },
    });

    const text = await res.text();

    if (res.status >= 400 && res.status < 600) {
      throw new ResponseError(text, res);
    }

    return { res, text };
  }
}
```
@yuchenshi  The code snippet about could work?

**Comment by yuchenshi** [comment]
@Villanuevand I think `Content-Type` breaks the upload, but not `Authorization`. Could you please send me a PR for adding the `Authorization` header only?

**Comment by Villanuevand** [comment]
> @Villanuevand I think `Content-Type` breaks the upload, but not `Authorization`. Could you please send me a PR for adding the `Authorization` header only?

Sure I'll do 🤓

**Comment by Villanuevand** [comment]
@yuchenshi 

PR #383

**Comment by yuchenshi** [comment]
This is now finally fixed and a release will come out soon. Thanks @quantuminformation @Villanuevand for the help!
