### ISSUE TITLE
Firestore collections nested under empty documents are not visible

### ISSUE THREAD

**Issue by Methodician** [firebase/firebase-tools-ui#369]
**Issue:** The emulator suite fails to display data nested under an empty document.

Example data structure: 
> visibleCollection > {docId} > DATA
> invisibleCollection > emptyDoc > invisibleSubCollection > DATA
> visibleNestingCollection > nonEmptyDoc > visibleNestedSubCollection > DATA

The first and last will show up in both the Firebase Console and the Firebase Emulator Suite.
The middle one shows up on the Firebase Console but not in the Emulator Suite

**MCVE repo for your convenience:** https://github.com/Methodician/firestore-emulator-bug-mcve

**Back story:**
I had been using what may be an unusual way of organizing my data given the constraints of the collection/document/collection/document structure of Firestore. It has been working nicely for me, until I decided to give the new emulator suite a test run (amazing tools at last! No more crappy local testing experience! YAY FIREBASE TEAM!)
I thought something was wrong with my implementation at first but then I saw that the emulators were working. I spent hours trying to suss out what I was doing "wrong" but it turns out I was just doing something "different" so I spent hours figuring out exactly what that was and then creating a simple demonstration repo. I hope it helps, and please fix!

**Comment by yuchenshi** [comment]
Thanks for the report! This is a known issue #273 and we're working on it.
Great job on the MCVE repo!

**Comment by Methodician** [comment]
ty
