### ISSUE TITLE
Emulator UI does not show up on Windows w/ WSL2 (current 332 workarounds do not work)

### ISSUE THREAD

**Issue by b0ot** [firebase/firebase-tools-ui#377]
Browser: Google Chrome (Also tested firefox/edge)
Browser version: Version 86.0.4240.75 (Official Build) (64-bit)
Operating system: Windows 10 Pro Version 2004
Running WSL2 with Ubuntu 20.04
uname -r : 4.19.128-microsoft-standard
Operating system version:

What steps will reproduce the problem:
Following along with the Google Codelab for Emulators
https://developers.google.com/codelabs/firebase-emulator-get-started#2

1. I follow the through step 3 (no issues yet)
2. On step 4 I run firebase emulators: start 

What is the expected result?
I should be able to login web UI via localhost:4000

What happens instead of that?
The emulators seems to start ok
```
tom-linux@DESKTOP:~/emulators-codelab/codelab-initial-state$ firebase emulators:start
i  emulators: Starting emulators: functions, firestore, hosting
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, pubsub
⚠  Your requested "node" version "8" doesn't match your global version "12"
i  firestore: Firestore Emulator logging to firestore-debug.log
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/home/tom-linux/emulators-codelab/codelab-initial-state/functions" for Cloud Functions...
✔  functions[calculateCart]: firestore function initialized.

┌───────────────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! View status and logs at http://localhost:4000 │
└───────────────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5001 │ http://localhost:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:8080 │ http://localhost:4000/firestore │
├───────────┼────────────────┼─────────────────────────────────┤
│ Hosting   │ localhost:5000 │ n/a                             │
└───────────┴────────────────┴─────────────────────────────────┘
  Other reserved ports: 4400, 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
```
However I can't access the UI via any web browser
I get Error: ERR_CONNECTION_RESET

At first this seems very similar to: 
https://github.com/firebase/firebase-tools-ui/issues/332

However users in that thread were able to
1.) Access the UI using the linux host IP address in place of local host
2.) Had a successful work-around using: microsoft/WSL#5706 (comment)
That leads to running a custom script here: [#4150 (comment) ](https://github.com/microsoft/WSL/issues/4150#issuecomment-667621988)
After adding additional ports: 22,80,443,8080,10000,3000,4000,5000,5001,8081,8082,4200,3128,4400,4500 

**However both of the above workarounds do not work with my setup.**

Additional Debug Logs
[firebase-debug.log](https://github.com/firebase/emulators-codelab/files/5396772/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/emulators-codelab/files/5396773/firestore-debug.log)
[ui-debug.log](https://github.com/firebase/emulators-codelab/files/5396774/ui-debug.log)

**Comment by yuchenshi** [comment]
This should be fixed with Firebase CLI v8.15.1. See https://github.com/firebase/firebase-tools-ui/issues/332#issuecomment-722742959 for details. If you still see the issue, just kindly open a new issue in firebase-tools.
