### ISSUE TITLE
Can't display field filter anymore

### ISSUE THREAD

**Issue by tr4g** [firebase/firebase-tools-ui#387]
### [REQUIRED] Environment info

**firebase-tools:**
8.13.1

**Platform:**
Linux on Docker (WSL 2)

### [REQUIRED] Test case

I'm trying to accomplish something that has been possible in both the cloud version and the emulator version of Firestore: show filtered parameter on each document of a collection:

**Works fine on the cloud version:**
![firestore-online](https://user-images.githubusercontent.com/197329/97012236-0a3e7680-151e-11eb-8ee8-20bffa78edb4.jpg)

**Stopped working on local version:**
![firestore-local](https://user-images.githubusercontent.com/197329/97012339-2510eb00-151e-11eb-9860-4d4fe5cbd480.jpg)

### [REQUIRED] Steps to reproduce

Run the emmulator, create a collection and a couple documents, try fo filter by any parameter

### [REQUIRED] Expected behavior

Should have the same behavior as the cloud version, and show the filtered parameter

### [REQUIRED] Actual behavior

Doesn't

**Comment by samtstern** [comment]
Moving this issue to firebase-tools-ui since it's about the Emulator UI

**Comment by tr4g** [comment]
i'd like to think people at firebase cares

**Comment by yuchenshi** [comment]
Thanks for the bug report!
After hours of digging, this looks like a bug in React (or more precisely speaking, React legacy mode + Suspense) and I've hot fixed it for now. A release is coming out soon.

----

Note to the team: A proper fix would be switching to React DOM experimental [blocking / concurrent mode](https://reactjs.org/docs/concurrent-mode-adoption.html).
