### ISSUE TITLE
Firebase Authenticator UI 

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-tools-ui#399]
https://firebase.google.com/docs/emulator-suite/connect_auth?authuser=0#web 

<img width="1367" alt="Screen Shot 2020-10-30 at 1 24 07 PM" src="https://user-images.githubusercontent.com/4000076/97737473-73406400-1ab3-11eb-8744-64f47a16c9df.png">

I would like to know where I am saving the SDK in which file so it can work. 

```
firebase.auth().useEmulator('http://localhost:9099/');

export FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
```

This code should be written on which page because it's not working where I have initialized FirebaseUI

**Comment by yuchenshi** [comment]
Assuming you've followed FirebaseUI [setup guide](https://github.com/firebase/firebaseui-web/blob/master/README.md#using-firebaseui-for-authentication), you should have a line like:

```js
var ui = new firebaseui.auth.AuthUI(firebase.auth());
```

Now put `firebase.auth().useEmulator('http://localhost:9099/');` immediate before that line, like:

```js
firebase.auth().useEmulator('http://localhost:9099/');
var ui = new firebaseui.auth.AuthUI(firebase.auth());
```

And you should be good to go.

**Comment by JamesVanWaza** [comment]
@yuchenshi, thank you, it should also be placed in documentation so it's easier to setup.
