### ISSUE TITLE
Firebase auth emulator data export not working

### ISSUE THREAD

**Issue by PuruVJ** [firebase/firebase-tools-ui#406]
When I add a new user in the newly released firebase auth emulator, and then shut down the emulator, started with command:

```bash
firebase emulators:start --export-on-exit --import em-data
``` 

the users are not retained when I restart the emulators, while firestore and RTDB are.

**Comment by yuchenshi** [comment]
Duplicate of https://github.com/firebase/firebase-tools/issues/2749
