### ISSUE TITLE
api.tsx:51 Uncaught (in promise) Error: .set() on an existing document would delete other fields

### ISSUE THREAD

**Issue by bradintheusa** [firebase/firebase-tools-ui#437]
Hi

Trying to add new data after deleting. This is more of an FYI & feedback.
-- This is from the Chrome console.

```
api.tsx:51 Uncaught (in promise) Error: .set() on an existing document would delete other fields
    at api.tsx:51
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

Restarting the server did not help.

Brad.

[firebase-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611359/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611360/firestore-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611361/ui-debug.log)
[database-debug.log](https://github.com/firebase/firebase-tools-ui/files/5611362/database-debug.log)

**Comment by yuchenshi** [comment]
Would you please give a bit more details on how you ran into the error? A step-by-step repro would be great. Feel free to use screenshots if they help!

**Comment by bradintheusa** [comment]
Sure. I'll try to reproduce.   Basically I deleted a document and then tried to add it back.  The delete went fine but the adding it back is what caused the error.

**Comment by bradintheusa** [comment]
Sorry I've not had a chance to recreate.  I'll close for now and reopen when I have time to document it.

**Comment by edmondklai** [comment]
Step to reproduce this error:

1. Create an empty Firestore document with console in production.
2. Create subcollection for that document.
3. Populate the subcollection with documents.
4. Copy the data locally.
5. Run emulators with the test data.


![2021-02-16 23 27 26](https://user-images.githubusercontent.com/23513440/108160402-9ddc1a00-70ae-11eb-882f-a7c47adca5b9.gif)

**Comment by yuchenshi** [comment]
Thanks for the clear steps! I can repro this even without using production dumps. It seems creating a document and then deleting all its field can also turn it into empty and trigger this.
