### ISSUE TITLE
Firestore document fields, subcollections and map keys are not in lexicographical order

### ISSUE THREAD

**Issue by GabriFila** [firebase/firebase-tools-ui#438]
_I haven't found any issue template, please tell me if I need to edit this._

### Problem
I've noticed that in the local firestore UI the fields of a document, its subcollections and the fields of a map inside the document are not lexicographically ordered.
![actual](https://user-images.githubusercontent.com/32385294/100726004-ab91d580-33c4-11eb-8749-60a72f42b1da.png)

### To reproduce
1. Startup the firestore emulator.
1. Create a new collection `temp`
1. Create a new doc `temp`
1. Add fields and fields in non-lexicographical order, e.g `Z: "Z"`, `F: "F"`, `A: "A"`,`G: "G"`.
1. They are ordered by the added time, not lexicographically

### Expected behavior
In the Firestore web UI the lexicographical order is followed.
![expected](https://user-images.githubusercontent.com/32385294/100726009-acc30280-33c4-11eb-8e44-16cf308b7744.png)

### Motivation
I believe it should be that way to give consistency between the two environments, to help also the developer when confronting the 2 DBs.

### Fix
It should not be difficult to fix by adding a sort method when mapping the keys to the great components. I would be very happy to do it.

Thank you

**Comment by yuchenshi** [comment]
Sure, just send us a Pull Request!
