### ISSUE TITLE
Firestore Emulator stop work after import/export data

### ISSUE THREAD

**Issue by mateusdias** [firebase/firebase-tools-ui#491]
A few hours ago I tried to import / export data from the firestore emulator by --import ... and I don't know why, but the web interface of the emulator, which manages the collections, stopped working - always 0 collections, I cannot add, don't show data... unusable. When I try to add a collection, it doesn't add, it doesn't clean, anyway ... it didn't work anymore. I haven't updated anything at all. I just tried to use the commands: exec, import / export and start with the --import option

I tried many times to shut down and restart the emulator, stop, and kill the process, even remove the Firebase CLI package and reinstall globally. Unsuccessfully.

I looked at the log files, debug and ui debug, nothing different came up ...

Chrome: Version 87.0.4280.141
Safari: Version 14.0.2 (15610.3.7.1.10, 15610)
macOS Catalina 10.15.7 (19H114)
firebase --version: 9.2.2

Video: 

https://user-images.githubusercontent.com/5657806/105580857-aff7c080-5d6d-11eb-8ce1-d54fb9d3cfc1.mov

**Comment by yuchenshi** [comment]
Would you mind looking into two more places for logs?

* Chrome Developer Tools (Console tab) on the Emulator UI
* `firestore-debug.log`

Those two places (especially console) are more likely to contain useful information. Make sure to keep the developer tools open while you go through the steps you did in the video -- you should see something new printed out.

**Comment by mateusdias** [comment]
> Would you mind looking into two more places for logs?
> 
> * Chrome Developer Tools (Console tab) on the Emulator UI
> * `firestore-debug.log`
> 
> Those two places (especially console) are more likely to contain useful information. Make sure to keep the developer tools open while you go through the steps you did in the video -- you should see something new printed out.

Hi Dear! 

Nothing special or detailed in the logs. Really. 

I recreated the project, starting from a new one, migrating the sources and the problem was solved. Of course, this was not the best solution. But, something wrong that I don't know what happened when I tried to import / export data specifically for a project and crash emulator completely! 

Sorry for the delay in the response!
Thanks!

**Comment by yuchenshi** [comment]
It sounds like we need the actual export dump to see what is happening here. Closing for now, but would you mind contacting Firebase Support the next time this happens, and provide them the exported directory zipball?
