### ISSUE TITLE
Authentication custom claims <textarea> misbehaving

### ISSUE THREAD

**Issue by realStandal** [firebase/firebase-tools-ui#514]
Hello! I've a solution to my issue (I believe) not sure where to put it.

So if you resize the Custom Claims `<textarea>`, I'm assuming it applies to others, it'll resize below some content, not push other content out of the way, and block access to `input` elements below it.

Going through `firsebase-tools-ui's` source-code, y'all use `@rmwc/textfield`; its styling is what causes this issue, more specifically the styling of element `label.mdc-text-field--textarea`. [Textareas are supposed to have a fixed height](https://material.io/components/text-fields/web#input-types), yet in this case I'm throwing it out there it should allow and support a variable height, which would mean adding `height: auto` to the element I referenced.

I'm sure this is an issue which could also apply for `@rmwc/textfield`, again it kind of contradicts Material's standard; but at the same time, it's confusing to me as a user: if I have the option to resize the element I assume it'll treat that first-class, and accommodate the rest of the form.

**Comment by yuchenshi** [comment]
Would you mind bring this to rmwc on GitHub? As you've observed, the HTML and styling are in the library and we don't really have a clean fix in Emulator UI.
