### ISSUE TITLE
Emulator doesn't seem to be able to handle large imports

### ISSUE THREAD

**Issue by forsstromerik** [firebase/firebase-tools-ui#530]
I want to use the same data in Firestore in the Emulator as is used in production. Running the emulator and importing a subset of the data (~40MB) works. However, when I import the complete export from the production database, which is around 500MB, it doesn't seem to work.

The CLI gives no error when starting the emulator with the larger import. Under /firestore in the emulator UI it spins forever saying "Loading collections" though. I cannot view any data there. 

Trying to get documents from the Chrome DevTools Console gives me 

```
@firebase/firestore: Firestore (8.1.1): Could not reach Cloud Firestore backend. 
Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. 
The client will operate in offline mode until it is able to successfully connect to the backend.
```

It seems like I am missing something here. Because I find it very strange that I shouldn't be able to run on 500MBs worth of data in the emulator.

**Comment by yuchenshi** [comment]
We can definitely look into this, but we'd need the export dump to investigate. Would you mind reaching out to Firebase Support at https://firebase.google.com/support/troubleshooter/contact? You can share your production export confidentially that way.

**Comment by forsstromerik** [comment]
Thank you. I will contact support then 👍
