### ISSUE TITLE
Windows can't open the development server

### ISSUE THREAD

**Issue by varunarora** [firebase/firebase-tools-ui#54]
This is likely a react app starting issue. I am using WSL / Ubuntu 16.04.

Upon running:

```
firebase emulators:exec --project sample --only database,firestore --import test-data 'npm start'
```

I get a window that says:

![image](https://user-images.githubusercontent.com/629203/77023950-759de580-694a-11ea-962d-d18572d46d08.png)

This isn't a major inconvenience, since I can just open the URL in the browser directly.

**Comment by yuchenshi** [comment]
This is probably something with `react-scripts`. Try creating a blank react app using https://github.com/facebook/create-react-app and see if you also get that. If so, please report an issue with them.
