### ISSUE TITLE
Firestore Emulator UI does not scroll

### ISSUE THREAD

**Issue by zurrutik** [firebase/firebase-tools-ui#540]
When you add a map(or an array) and start adding values in the Firestore Emulator UI, there is no scrollbar on the right hand side to reach the end of the panel therefore I cant reach the buttons to confirm my changes. The screen capture attached is self explanatory

Could you please fix it? 

![no-scrollbar](https://user-images.githubusercontent.com/38129877/113403197-8b8c1600-93a6-11eb-9687-4f8b8f61fd67.png)

**Comment by ZYinMD** [comment]
This is also true when editing a field: if the field is near the bottom of the screen, and you click the Pen icon to edit it, the "save" button won't be visible. (you could get to it by pressing `tab`, but not everybody knows this.)

**Comment by weixifan** [comment]
Thank you for reporting this; I've filed an internal issue b/189044279 to track this.

**Comment by yuchenshi** [comment]
Fixed went out with Firebase CLI v9.17.0.
