### ISSUE TITLE
unable to run local env vs firebase emulator auth/network-request-failed

### ISSUE THREAD

**Issue by vitaly87** [firebase/firebase-tools-ui#547]
Hi all.
I am trying to run web ui and firebase emulator the issue that I am getting error:

`code: "auth/network-request-failed" message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."`

init the simulator

```

if (window.location.hostname === "localhost") {
    console.log("localhost detected!");
    firebase.auth().useEmulator("http://localhost:9099");
    firebase.database().useEmulator("localhost", 9000);
  }
```

my code for login

```
 firebase
      .auth()
      .signInWithEmailAndPassword(email, password)
      .then((userCredential) => {
```

**Comment by malcolmdeck** [comment]
Hello! This appears to be an issue with one of: the JS SDK, the JS UI SDK, or the Firebase emulator. (My guess is the JS UI SDK). Can you please file this in the appropriate place?
JS SDK: https://github.com/firebase/firebase-js-sdk/issues
JS-UI SDK: https://github.com/firebase/firebaseui-web/issues
Emulator: https://github.com/firebase/firebase-tools/issues
