### ISSUE TITLE
The ability to delete collections      label:"feature request"  

### ISSUE THREAD

**Issue by Pingear** [firebase/firebase-tools-ui#548]
Please create the ability to delete collections in the Firestore emulator. Such -
![delete_collections](https://user-images.githubusercontent.com/16469484/115158557-6fbb8c00-a097-11eb-9e22-8e94fec3ce0f.gif)

**Comment by yuchenshi** [comment]
Hi, thanks for filing this feature request! We are unable to promise any timeline for this, but if others also have this request, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: b/186652774)

**Comment by yuchenshi** [comment]
Released in latest Firebase CLI.
