### ISSUE TITLE
npm start typescript compile fails

### ISSUE THREAD

**Issue by varunarora** [firebase/firebase-tools-ui#55]
Upon trying to start the development server, the compilation fails with the following message:

```
Failed to compile.

./src/components/Firestore/utils.ts
  Line 70:22:  Parsing error: Expression expected
```

This is coming from the line:
```
  return typeof value?.valueOf() === 'boolean';
```

My typescript is bad, otherwise I'd have PR'ed a fix. This change came from #44.

**Comment by yuchenshi** [comment]
FYI we just updated typescript version so you will need to `npm install`. If that still fails then please `rm -rf node_modules && npm install`.
