### ISSUE TITLE
Emulator doesn't close ports when ending session

### ISSUE THREAD

**Issue by ZiyadF296** [firebase/firebase-tools-ui#578]
I have been running and using the emulator for quite a while now. However, whenever I end the session, the ports do not close.

For example, I have the port localhost:4000 for the Emulator UI. When I need to end the session, I do that. However, when I come to rerun the emulator again, I get the error saying that the port is already taken:

```java
!  ui: Port 4000 is not open on localhost, could not start Emulator UI.
!  ui: To select a different host/port, specify that host/port in a firebase.json config file:
      {
        // ...
        "emulators": {
          "ui": {
            "host": "HOST",
            "port": "PORT"
          }
        }
      }
i  emulators: Shutting down emulators.

Error: Could not start Emulator UI, port taken.
```

The only solution currently I have in mind is to restart my machine to close that port. I am sure there are software tools I can install to manage the ports that are opened and running. But it would definitely be better if it would automatically close the ports after I end the session.

Also, is there any correct way of ending the session? I am currently just closing the terminal and the pop-ups that show when running the emulator, but that doesn't seem to work.

**Comment by yuchenshi** [comment]
Press Ctrl-C should give the Firebase CLI a chance to shut down the emulators one by one, as seen in the logs. After no process is running you can safely close the terminal.

**Comment by mowliv** [comment]
Is this the only solution? It sure would be nice to have a way to fix this. I would generally do a control-C but, for example, I just had to kill off the whole terminal app and now it's wedged.
