### ISSUE TITLE
Cannot enter timestamp field on document in Firestore

### ISSUE THREAD

**Issue by wtpalexander** [firebase/firebase-tools-ui#601]
Firebase tools version: 9.12.1
Safari 14.1.1
macOS Big Sur

When creating a timestamp field entry on a document using the Firestore Emulator UI, the autocorrect logic provided by Safari prevents saving the new field. No date I enter is accepted by the autocorrect logic, preventing me from pressing save.

![Screenshot 2021-06-28 at 9 37 35 am](https://user-images.githubusercontent.com/7461082/123606137-7fbcbe00-d7f4-11eb-95de-9851e73e644d.png)

**Comment by yuchenshi** [comment]
Hi, could you please try 06/28/2021 instead and let me know if it works? Depending on your language and region settings, your browser may expect MM/YY/DDDD format (where month come first). Unfortunately, the Emulator UI has very little control over that.

**Comment by wtpalexander** [comment]
Hi @yuchenshi, I don't seem to be able to enter a date in that format either? See attached screenshot. The browser prevents me from entering 06/28/2021 since 28>12 but when I enter 1/1/2022 it still fails. 

<img width="658" alt="Screenshot 2021-06-29 at 8 57 06 am" src="https://user-images.githubusercontent.com/7461082/123759817-29b14e80-d8b8-11eb-98d0-bd24cee27d78.png">

I assume this could be why the production emulators use a custom date/time entry method with separate fields?

**Comment by jakeleventhal** [comment]
Encountering this on with `firebase-tools: 10.7.1` on macOS (Safari Version 15.4)

**Comment by gianlucatomasino** [comment]
Created a PR with a fix. A possible workaround in the meanwhile a think is to remove seconds from the field.

**Comment by wtpalexander** [comment]
#769 Solves this issue.
