### ISSUE TITLE
Firewall Issue

### ISSUE THREAD

**Issue by sgarg15** [firebase/firebase-tools-ui#618]
Hey everyone, so i was trying to setup firebase emulator in flutter and I followed this tutorial :
[Emulator Start Video](https://www.youtube.com/watch?v=XgLq1kVCxTQ&lc=Ugy_UfZEH9_SuLw4DQZ4AaABAg.9Q7bBF3J5sb9Q7gJbeqmjV&ab_channel=FilledStacks)

And as I am using a real device, I changed the local host as the host to my IPV4 address which i found through ipconfig, as the tutorial suggested.

But I keep getting an error saying:
`[firebase_auth/network-request-failed] A network error (such as timeout, interrupted connection or unreachable host) has occurred.`
When I try to log in or sign up with firebase auth.
If i try without the emulation and using normal firebase, it works perfectly fine.
Any ideas why that may be?
This is the code I have currently:
```dart
const bool USE_EMULATOR = true;

  if (USE_EMULATOR) {
    const localHostString = 'myIPV4numbers';
    // [Firestore | localhost:8080]
    FirebaseFirestore.instance.settings = const Settings(
      host: "$localHostString:8080",
      sslEnabled: false,
      persistenceEnabled: false,
    );

    // [Authentication | localhost:9099]
    await FirebaseAuth.instance.useEmulator('http://$localHostString:9099');

    // [Storage | localhost:9199]
    await FirebaseStorage.instance.useStorageEmulator(
      '$localHostString',
      9199,
    );

    FirebaseFunctions functions = FirebaseFunctions.instance;
    functions.useFunctionsEmulator("$localHostString", 5001);
  }
```
and my firebase debug logs look like the following:
`
[debug] [2021-07-23T18:31:33.203Z] Jul 23, 2021 11:31:33 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Jul 23, 2021 11:31:33 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
 `
 i added this `android:usesCleartextTraffic="true"` into my debug AndroidManifest as well.
 
 I tried disabling my mcafee firewall to see if that was the issue, and it apparently was. Once I turned off the firewall the emulator was working like it should. 
 
So now my question was, what and how should I add to my firewall exceptions so that the emulator worked without me having my firewall turned off?

Any help will be appreciated.
Thank you!

**Comment by yuchenshi** [comment]
Thanks for the question. We'd appreciate it if you repost this to [StackOverflow](https://stackoverflow.com/questions/tagged/firebase){target="_blank"}. That will help other community members who may have the same question. We respond to StackOverflow questions each day, so you should get a quick answer. Thanks again.
