### ISSUE TITLE
Access Emulator UI via IP local

### ISSUE THREAD

**Issue by ithustle** [firebase/firebase-tools-ui#626]
Hi, there.

Is there a way to access emulator UI from local IP?
I have a centralized pc where I installed firebase emulator for my teams works and I'd like to them can access the logs from emulators ui. 

I tried do something like but no luck

firebase.json

````
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "functions": {
      "port": 5001,
      "host": "0.0.0.0"
    },
    "storage": {
      "port": 9199,
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true,
"port": "local_ip" <---- I inserted this
    },
    "auth": {
      "port": 9099,
      "host": "0.0.0.0"
    },
    "firestore": {
      "port": 8080,
      "host": "0.0.0.0"
    }
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }
}


````

**Comment by yuchenshi** [comment]
`port` is for the port number, which can be omitted for any available port. You'd want *host* instead for specifying host IP addresses.

See https://github.com/firebase/firebase-tools-ui/issues/340#issuecomment-876784162 for an example snippet -- and note that there are more emulator-like services that also needs to be specified and see caveats there.
