### ISSUE TITLE
Firebase functions authentication: Custom Claims Not Added 

### ISSUE THREAD

**Issue by YasBenAll** [firebase/firebase-tools-ui#642]
I'm adding the claim to a user's profile that he or she paid for something, though, after the payment this attribute isn't visible. I'm running the functions on an emulator on a local host. 

This is the code I'm using: 
  
```
  exports.addPaidClaim = functions.https.onCall((data, context) => {
    // get user and add custom claim (paid)
    return admin.auth().setCustomUserClaims(data.uid, {
      paid: true,
    }).then(() => {
      return {
        message: `Success! ${data.email} has paid the course`,
      };
    }).catch((err) => {
      return err;
    });
  });
```

I've refreshed the page and checked the user attributes afterwards through console.log to see if the attribute had been added, but this is not the case. What should I do?

**Comment by yuchenshi** [comment]
Have you re-authenticated on the client side? Same as production, [custom claims are added to new tokens issued AFTER you set them, not existing sessions](https://firebase.google.com/docs/auth/admin/custom-claims#propagate_custom_claims_to_the_client). You may want to force a token refresh or re-authentication after the function call *on the client side* -- see the link for details.
