### ISSUE TITLE
Offline Icons & Fonts needed

### ISSUE THREAD

**Issue by amancoder28** [firebase/firebase-tools-ui#653]
First of all I would like to say you have made a great tool for firebase developers, Thanks for that.

Mostly I dont have internet connection nearby because my pc is old. but I can connect with my mobile with Usb tethering to use my mobile date in my pc.

Recently I have downloade firebase cli, run firebase init & setup emulators ui. but when i restart my pc i lost all the icons in the emulator ui.

I am really disappointed how it looks beacause I cant get an Internet connection nearby the icons & fonts are lost because the emulator ui needs to get material icons & roboto font from the web. but i cant get a connection nearby.

Please make all the icons & fonts to work offline as the emulator ui is a local web app for local development & testing.

![Screenshot (116)](https://user-images.githubusercontent.com/60542770/135953893-e14d8608-2306-4812-a4e3-d267d2dac3da.png)

![Screenshot (104)](https://user-images.githubusercontent.com/60542770/135953931-73512c40-8877-4aae-9bcd-4876bd0e1060.png)

![Screenshot (111)](https://user-images.githubusercontent.com/60542770/135953966-2d730b77-8573-486b-9913-5df05aa4453d.png)

![Screenshot (108)](https://user-images.githubusercontent.com/60542770/135954026-b3b34392-b6b5-49c7-9d82-21435bcaf146.png)

**Comment by lisajian** [comment]
Hi, thanks for filing this feature request! We are unable to promise any timeline for this, but if others also have this request, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: b/208893888)

**Comment by amancoder28** [comment]
thanks these could help a lot! if there is a simple service worker these kind of problems will be fixed!
