### ISSUE TITLE
Does not support emulator urls using HTTPS

### ISSUE THREAD

**Issue by BobbieGoede** [firebase/firebase-tools-ui#666]
For local development I'm trying to run firebase emulators in a docker container, this works fine, but the dashboard does not work since the base urls are hardcoded to be insecure. I'm not sure if this is intended to prevent running emulators behind a reverse proxy with ssl.

Because the dashboard will run on a secure url, insecure api calls will fail like so:
```
api.ts:102 Mixed Content: The page at 'https://domain.test:4050/auth' was loaded over HTTPS, but requested an insecure resource 'http://domain.test:9099/emulator/v1/projects/project-id/config'. This request has been blocked; the content must be served over HTTPS.
```

Base url protocol is hardcoded as seen here:
https://github.com/firebase/firebase-tools-ui/blob/3ef507ed499c4f1ad4c6a60926b12f2f7534c54b/src/components/Auth/api.ts#L40

**Comment by yuchenshi** [comment]
Now supported in CLI v11.14.0. It's not perfect, especially not all emulators work over HTTPS, but we think it's a step in the right direction. Let us know if you run into issues and PRs are welcomed!
