### ISSUE TITLE
Emulator UI does not fit in Microsoft Edge

### ISSUE THREAD

**Issue by Zujaj** [firebase/firebase-tools-ui#668]
**Windows 10 Pro Version 21H1**

The emulator UI does not fit in the Edge browser, where as it looks perfectly on Mozilla Firefox.

**Microsoft Edge**
Version 96.0.1054.43 (Official build) (64-bit)

![Emulator-in-Edge](https://user-images.githubusercontent.com/46039324/145215631-3e5e46ee-5ba6-43ba-bf88-fb8321eaa248.gif)

**Mozilla Firefox Snapshot**

![Emulator in FireFox](https://user-images.githubusercontent.com/46039324/145215532-7b6a6fd0-5f16-4143-9b8d-5e84d2e22a81.png)

**Comment by yuchenshi** [comment]
cc @bkendall to help reproducing this on Windows

**Comment by bkendall** [comment]
I'm unable to reproduce the issue. My version of Edge (on Windows 11) is `98.0.1108.43`.

![image](https://user-images.githubusercontent.com/160236/152875624-c187228a-a6c3-41e9-8e13-649b5b4d3176.png)

**Comment by Zujaj** [comment]
@bkendall Maybe this issue occurred due to some chrome extension. The UI worked perfectly when I copy-pasted the `localhost` address in the InPrivate browsing.

**Comment by yuchenshi** [comment]
Looks like this is outside our control. ProTip: Feel free to disable all your extensions and enable them one by one to see which one is causing the problem. Or, feel free to just use Emulator UI in private browsing -- it doesn't really need any cookies / storage to work.
