### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ':' on Auth emulator using Google Provider

### ISSUE THREAD

**Issue by anhzf** [firebase/firebase-tools-ui#679]
# Problems
I just installed new nodejs on my computer then installs and set up the firebase CLI as usual. Initialize my new folder project with firebase CLI (Until this I can conclude if the emulator and the CLI are the newest). then, Setting up my project for Google Authentication. When I try my code and try to log in I was redirected to the Google login page as usual. **But, I can't click anything in that's page.** (both happen in the popup and redirect).

# What I've to try
when I check the console there's found ```Uncaught SyntaxError: Unexpected token ':'```. Goto, the source panel in devtools to check where's the error and I found this:
![image](https://user-images.githubusercontent.com/36941633/149648882-6559a286-a8ed-4a61-8f3f-e4717c574e79.png)

# environment info:
Firebase CLI Version: 10.1.0
Nodejs: 16.13.2

Thank you!

**Comment by DibyodyutiMondal** [comment]
reverting to `firebase-tools@10.0.1` fixes it for me
I have same node version

**Comment by anhzf** [comment]
> reverting to `firebase-tools@10.0.1` fixes it for me I have same node version

Thank you it works for me too.
I hope it will be fixed ASAP

**Comment by yuchenshi** [comment]
Fixed by https://github.com/firebase/firebase-tools/pull/4016

Release coming soon
