### ISSUE TITLE
Firestore emulator UI not seeing any data but queries work

### ISSUE THREAD

**Issue by dadixon** [firebase/firebase-tools-ui#707]
I'm building an iOS app and testing with the Firestore emulators. That Authentication emulator works great. I can create a user in the app and I see it in the UI. Unfortunately that's not the case with the Firestore emulator UI. I can create objects in there and retrieve them but the UI doesn't change at all. The clear all data button doesn't work either.

**Comment by yuchenshi** [comment]
Thanks for the report. I think you've ran into a Project ID mismatch. While you can write data to any valid project ID using the SDKs, the Emulator UI only shows data in the default project ID. You can try starting the emulators with `firebase emulators:start --project foo-bar`, where `foo-bar` matches what your iOS app is using, and you should be able to see the data now.
