### ISSUE TITLE
Firestore Data Nothing showing

### ISSUE THREAD

**Issue by dadixon** [firebase/firebase-tools-ui#709]
I have an iOS app that is using the Firestore and FireAuth emulators. Creating accounts shows in the emulator but saving data doesn't. I can retrieve the data but the UI doesn't reflect my data.

**Comment by yuchenshi** [comment]
Would you mind checking the Project ID you're using on the iOS app, and make sure the Emulator Suite is also using the same Project ID? For example, you can use `firebase emulators:start --project foo-bar` to start the emulators if your iOS app is trying to write to `foo-bar`.

**Comment by dadixon** [comment]
Yes the product ID is correct on my emulators. I still don't see any data in the emulator UI.

**Comment by dadixon** [comment]
1. I cleared all my data. 
2. Erased all content in the simulator.
3. Started the app
4. Created an account. (This also stores data in a collection but it's empty)
5. Authentication shows the user
6. Firestore doesn't
![Screen Shot 2022-03-07 at 9 27 15 AM](https://user-images.githubusercontent.com/1591018/157052867-1c2717f3-8150-4f48-a0d5-0031d91335dc.png)


![Screen Shot 2022-03-07 at 9 27 36 AM](https://user-images.githubusercontent.com/1591018/157052941-789bf856-20cb-4c19-862a-bb71deea94e2.png)
