### ISSUE TITLE
Storage Emulator UI should filter out zero-byte folder placeholders

### ISSUE THREAD

**Issue by tonyjhuang** [firebase/firebase-tools-ui#728]
Example of incorrect behavior:

<img width="1025" alt="Screen Shot 2022-03-16 at 9 20 21 PM" src="https://user-images.githubusercontent.com/1237337/158718015-dc8c2f3d-aa5d-43a0-893f-19cdf71fbe19.png">

The UI should filter these files out before rendering the view, like similar to how the Firebase and GCS cloud consoles behave.

**Comment by yuchenshi** [comment]
What is a good condition to catch these files? Is zero bytes in size && file name ends with `/` a good signal, or will it have false positives or negatives?

**Comment by tonyjhuang** [comment]
We should investigate what the SDKs do and see if there's a similar pattern of behavior.

**Comment by yuchenshi** [comment]
Fixed by https://github.com/firebase/firebase-tools/pull/4493
