### ISSUE TITLE
Create new folder in Storage Console does nothing

### ISSUE THREAD

**Issue by coreform** [firebase/firebase-tools-ui#738]
A button allows the user to enter a folder name and press a create button, setting the expectation that a new folder should be created and visible in the Storage list/hierarchy.

Given that Firebase guidance for determining the user (via uid) of the upload is to set the uid in metadata or in the path for the upload - neither of these methods is facilitated by the Emulator Console.

**Comment by flikkr** [comment]
I experienced the same thing.

**Comment by invisispider** [comment]
I am experiencing this currently. I noticed the duplicate question that redirected here. I inspect network request for "Create Folder":
{"error":{"code":400,"message":"Failed to parse multipart request body part. Missing content type."}}

**Comment by scadasystems** [comment]
You can create a folder by editing the address before uploading the file.

**Comment by coreform** [comment]
> You can create a folder by editing the address before uploading the file.

I don't see a way to do what you are describing via Firebase Emulator Console/GUI/Suite. Are you describing the use of the APIs/SDKs rather than the emulator console?

FYI what I've gone for so far is a CloudFunction that initializes my system and I call that from the command line after starting the emulators.

**Comment by SohelIslamImran** [comment]
How to import storage production data in local emulator??

**Comment by Drew-Daniels** [comment]
Experiencing problem as well on Firebase Tools 10.7.1.

**Comment by alvinchevolleaux** [comment]
> You can create a folder by editing the address before uploading the file.

Can you explain what you mean here? What address needs to be edited?

**Comment by yuchenshi** [comment]
Fixed in Firebase CLI v10.7.2. You should be able to create folders as usual through the Emulator UI without any workaround after upgrade.
