### ISSUE TITLE
Seeding of users for the auth emulator

### ISSUE THREAD

**Issue by pascalbe-humanize** [firebase/firebase-tools-ui#740]
Hey, 

when testing applications via automated tests, it is common
- that you need a user for a test
- that you want to seed that in firestore which references to this specific test user (user ID)

Question: **Is it currently possible to achieve this?** 

From what I see from the docs, there is a nice seeding feature for firestore data. Seeding data into the auth emulator seems to only work by calling the REST endpoint for that. The REST endpoint does not allow us to pass a user-ID. This causes the probem, that it is not straightforward to seed related data in the auth and the firestore emulator.

So, if there is currently no straightforward way, I would file a feature request to:

> Seeding of users for the auth emulator is possible with hardcoded user IDs

Looking forward to thoughts and other responses.

**Comment by pascalbe-humanize** [comment]
Please let me know, if I should move this request somewhere else. I was not sure, if this is the right spot for it.

**Comment by pascalbe-dev** [comment]
I found out, that it should work with the existing emulator import and export functionality. 
https://firebase.google.com/docs/emulator-suite/install_and_configure#export_and_import_emulator_data

I did not look enough, sorry. My bad. 

-> can be closed.

**Comment by yuchenshi** [comment]
Thanks for the feedback. The export function is indeed the recommended solution here.
