### ISSUE TITLE
Weird omnipresent scrollbars

### ISSUE THREAD

**Issue by abakucz** [firebase/firebase-tools-ui#757]
This is rather a minor issue, but eye-disturbing nevertheless.

Since recent updates I keep seeing unnecessary scrollbars everywhere in the Firestore Emulator UI.

![image](https://user-images.githubusercontent.com/49059299/167376385-b497ba46-f4ef-482e-9100-df5a47877a4b.png)

firebase-tools: 10.8.0
OS: Windows 10
Browsers: tested in all latest Chrome, Firefox and Edge

**Comment by yuchenshi** [comment]
This regression may have been introduced by https://github.com/firebase/firebase-tools-ui/pull/721

**Comment by yuchenshi** [comment]
Fixed in CLI v11.6.0
