### ISSUE TITLE
fs__default.realpathSync.native is not a function

### ISSUE THREAD

**Issue by hchiam** [firebase/firebase-tools-ui#820]
**Describe the bug**
Getting an error message that says `fs__default.realpathSync.native is not a function`

**To Reproduce**
```sh
gh repo fork firebase/firebase-tools-ui
cd firebase-tools-ui/
npm i
firebase emulators:exec --project demo-example --import test-data 'npm start'
```
You see the following on http://localhost:3000 :

**Screenshots**
<img width="837" alt="fs__default realpathSync native is not a function" src="https://user-images.githubusercontent.com/18131787/176354709-2c188cb7-c351-409f-80c8-c8bac0d0c7f5.png">

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome 102

**Extra info**
A quick Google search brings up https://github.com/facebook/jest/issues/10012 but the fix for Firebase Emulator still seems unclear as I am already running node v16.

**Comment by yuchenshi** [comment]
Just merged #849 and I think that should address this issue. Feel free to reopen if this issue persists after a fresh clone of the repo.
