### ISSUE TITLE
Can't able to see website output in local server on port http://localhost:3033

### ISSUE THREAD

**Issue by madhu-chinna** [firebase/firebase-tools-ui#833]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by christhompsongoogle** [comment]
Hi madhu-chinna, can you attach some logs of what might be happening? currently this issue is missing some screenshots or instructions on reproducibility.
