### ISSUE TITLE
Suddenly unable to access firebase console commands from emulaltor suite web ui dev tools console.

### ISSUE THREAD

**Issue by gerryau** [firebase/firebase-tools-ui#845]
**Describe the bug**
Since the latest update I can't seem to access the console from chrome dev tools when using firebase emulator suite. Now I get an error saying `firestore is not defined`.

**To Reproduce**

1. run `firebase emulators:start`
2. visit local hosting of emulator ui, e.g. `localhost:4000`.

**Expected behavior**
Able to use the console in browser to run commands to debug queries.

**Screenshots**
![image](https://user-images.githubusercontent.com/29995627/184528809-122318c4-a9e2-4563-a8ce-e3aa8fc7eac9.png)

**Desktop (please complete the following information):**

- OS: Tested on MacOS and Windows
- Browser Tried Chrome, Firefox.
- Version 

**Smartphone (please complete the following information):**

- Version `firebase tools --version` is 11.6.0

**Comment by gerryau** [comment]
Here's a better example of what was working but has now stopped working: https://twitter.com/fireship_dev/status/1267220417896255488

**Comment by christhompsongoogle** [comment]
So this was likely caused by the transition to the modular Javascript SDK in v9. The firebase object is no longer in the global space. See
https://github.com/firebase/firebase-tools-ui/commit/308a98d9a7b0dc3aba3228f701a01719fd3cb870

**Comment by gerryau** [comment]
Okay, is there any other way to achieve this, or is it just gone from the app alltogether?

**Comment by christhompsongoogle** [comment]
Currently that's correct. If you have a specific use-case you'd like to see covered by the UI it would be a big help to file a feature request so we can prioritize it if there's significant interest.

Related: 
https://github.com/firebase/firebase-tools-ui/issues/837

**Comment by gerryau** [comment]
Okay, so what version of firebase-tools can I downgrade to that this is working based on your link to commit?

**Comment by christhompsongoogle** [comment]
Based on the date of that change (June 23) I think the latest prior version would have been v11.1.0

[v11.1.0](https://github.com/firebase/firebase-tools/releases/tag/v11.1.0)
