### ISSUE TITLE
[Emulator UI] creating a sub-collection  doesn't work. you need to manually create it on the emulator.

### ISSUE THREAD

**Issue by johnberang12** [firebase/firebase-tools-ui#847]
i have a running emulator UI on port 4000 with authentication, functions, firestore, database, and storage.
everytime i try to save a data to the sub-collection, it doesnt persist. but when you manually create the subcollection, it will be created and the data you persisted will appear.
then if you navigate to the top level collections, the subCollection you've created will again disappear. what you need to do is to create the sub-collection again to get your sub-collections appear in the UI.

im using firebase CLI 11.7.0 
and node version 16.14.0

**Comment by yuchenshi** [comment]
Would you mind giving a bit more details and steps to reproduce? A video screencast will be awesome too

**Comment by johnberang12** [comment]
hi,
thanks for your reply. i have attached some picture and video as per
requested. I checked back the issue and it seems some stuffs are fixed.
idont pretty sure if its because i upgraded my firebase cli yesterday to
the latest version.
now, the only concern left is icant see in the emulator UI that there is a
sub collection in a specific document. as you can see from the photos  i
have a post which has a subcollection of "comments". and for every comment
it has a "subComment" subcollection. i cant see that in the emulator UI for
easy access. What i need to do is to manually create the comments
sub-collection inorder to see the documents under that sub-collection.
and as you can see on the video, after creating manually the sub-collection
and then going back to the home/top-level collections, the sub-collection
will disappear once again..
This may not be a total bug as there is a work around but it is very time
consuming especially if you have a sub-collection of sub-collections that
you need to monitor and you need to toggle back and forth from the home to
sub-collections and vice versa.

**Comment by johnberang12** [comment]
Since you are here, I wanted to take this opportunity to ask for some help.

I am honestly new to cloud functions and typescript. That's why I
don't have any idea what I'm doing here..

so, what i'm trying to do here is to :

1. increment and decrement the commentCounts field of a post when a new
comment is created or deleted
2. to increment and decrement the commentsCounts field of a comment when a
new subComment is created or deleted.
3. to update the auth displayName if a user is created.

there are all my functions:




import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

admin.initializeApp();

const db = admin.firestore();






//* update comment count
export const onCreateComment = functions.firestore
.document("posts/{postId}/comments/{commentId}")
.onCreate(async (snap, context)=> {
const postRefId = context.params.postId;
const snapRef = snap.ref;
const commentCollectionRef = snapRef.parent;
const postRef = commentCollectionRef.parent;
const postId = postRef?.id;
try {
return await db.collection("posts").doc(postId ?? postRefId)
.update({commentsCount: admin.firestore.FieldValue.increment(1)});
} catch (e) {
functions.logger.log(e);
throw e;
}
});

export const onDeleteComment = functions.firestore
.document("posts/{postId}/comments/{commentId}")
.onDelete(async (snap, context)=> {
const postRefId = context.params.postId;
const snapRef = snap.ref;
const commentCollectionRef = snapRef.parent;
const postRef = commentCollectionRef.parent;
const postId = postRef?.id;
try {
return await db.collection("posts").doc(postId ?? postRefId)
.update({commentsCount: admin.firestore.FieldValue.increment(-1)});
} catch (e) {
functions.logger.log(e);
throw e;
}
});


//* update subComment count

export const onCreateSubComment = functions.firestore
.document("posts/{postId}/comments/{commentId}/subComments/{subComment}")
.onCreate(async (snap, context) => {
const commentRefId = context.params.commentId;

const snapRef = snap.ref;
const subCommentCollectionRef = snapRef.parent;
const commentRef = subCommentCollectionRef.parent;
const commentId =commentRef?.id;
try {
return await db.collection("posts/{postId}/comments")
.doc(commentRefId ?? commentId )
.update({commentsCount: admin.firestore.FieldValue.increment(1)});
} catch (e) {
functions.logger.log(e);
throw e;
}
});

export const onDeleteSubComment = functions.firestore
.document("posts/{postId}/comments/{commentId}/subComments/{subComment}")
.onCreate(async (snap, context) => {
const commentRefId = context.params.commentId;
const snapRef = snap.ref;
const subCommentCollectionRef = snapRef.parent;
const commentRef = subCommentCollectionRef.parent;
const commentId = commentRef?.id;
try {
return await db.collection("posts/{postId}/comments")
.doc(commentRefId ?? commentId)
.update({commentsCount: admin.firestore.FieldValue.increment(-1)});
} catch (e) {
functions.logger.log(e);
throw e;
}
});


//* update auth display name

export const onUserCreate = functions.firestore
.document("users/{userId}").onCreate(async (snap, context) => {
const refId = context.params.userId;
const data = snap.data();
const displayName = data.displayName;
try {
return await admin.auth().updateUser(refId ?? refId, {
displayName: displayName,
});
} catch (e) {
functions.logger.log(e);
throw e;
}
});



on the onCreateComment and onDeleteComment, i got it working. It is
updating as expected but I'm not pretty sure if I'm handling it correctly.
If not, then please give me some tips on how to make that more robust.
and shall i use transaction here or using the FieldValue is enough?


Now, on my second and third todos, they are not working and giving me an
error which I can't understand why and how to fix it.

*on the onCreateSubComment and onDeleteSubComment functions this is the
error:*

i  functions: Beginning execution of "onDeleteSubComment"
>  {"severity":"INFO","message":"Error: 5 NOT_FOUND: no entity to update:
app: \"dev~muraita-main\"\npath <\n  Element {\n    type: \"posts\"\n
 name: \"{postId}\"\n  }\n  Element {\n    type: \"comments\"\n    name:
\"2022-09-01T12:55:24.748743\"\n  }\n>\n\n    at Object.callErrorFromStatus
***@***.***/grpc-js/build/src/call.js:31:19)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client.js:190:52)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:365:141)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:328:181)\n
   at
***@***.***/grpc-js/build/src/call-stream.js:188:78\n
   at processTicksAndRejections
(node:internal/process/task_queues:78:11)\nfor call at\n    at
ServiceClientImpl.makeUnaryRequest
***@***.***/grpc-js/build/src/client.js:160:30)\n
   at ServiceClientImpl.<anonymous>
***@***.***/grpc-js/build/src/make-client.js:105:19)\n
   at
***@***.***/firestore/build/src/v1/firestore_client.js:205:29\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16\n
   at repeat
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:118:13\n
   at OngoingCallPromise.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/call.js:67:27)\n
   at NormalApiCaller.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/createApiCall.js:81:30\n
   at processTicksAndRejections
(node:internal/process/task_queues:96:5)\nCaused by: Error\n    at
WriteBatch.commit
***@***.***/firestore/build/src/write-batch.js:417:23)\n
   at DocumentReference.update
***@***.***/firestore/build/src/reference.js:393:14)\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/lib/index.js:75:14\n
   at cloudFunction
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/firebase-functions/lib/cloud-functions.js:78:23)\n
   at
/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:578:16\n
   at runFunction
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:565:15)\n
   at runBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:577:11)\n
   at processBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:560:11)\n
   at invokeTrigger
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:641:19)\n
   at handleMessage
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:735:15)
{\n  code: 5,\n  details: 'no entity to update: app:
\"dev~muraita-main\"\\n' +\n    'path <\\n' +\n    '  Element {\\n' +\n
 '    type: \"posts\"\\n' +\n    '    name: \"{postId}\"\\n' +\n    '
 }\\n' +\n    '  Element {\\n' +\n    '    type: \"comments\"\\n' +\n    '
   name: \"2022-09-01T12:55:24.748743\"\\n' +\n    '  }\\n' +\n
 '>\\n',\n  metadata: Metadata {\n    internalRepr: Map(1) { 'content-type'
=> [Array] },\n    options: {}\n  },\n  note: 'Exception occurred in retry
method that was not classified as transient'\n}"}
⚠  functions: Error: 5 NOT_FOUND: no entity to update: app:
"dev~muraita-main"
path <
  Element {
    type: "posts"
    name: "{postId}"
  }
  Element {
    type: "comments"
    name: "2022-09-01T12:55:24.748743"
  }
>

    at Object.callErrorFromStatus
***@***.***/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:328:181)
    at
***@***.***/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest
***@***.***/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.<anonymous>
***@***.***/grpc-js/build/src/make-client.js:105:19)
    at
***@***.***/firestore/build/src/v1/firestore_client.js:205:29
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCallPromise.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/createApiCall.js:81:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Caused by: Error
    at WriteBatch.commit
***@***.***/firestore/build/src/write-batch.js:417:23)
    at DocumentReference.update
***@***.***/firestore/build/src/reference.js:393:14)
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/lib/index.js:75:14
    at cloudFunction
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/firebase-functions/lib/cloud-functions.js:78:23)
    at
/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:578:16
    at runFunction
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:565:15)
    at runBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:577:11)
    at processBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:560:11)
    at invokeTrigger
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:641:19)
    at handleMessage
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:735:15)
⚠  Your function was killed because it raised an unhandled error.
i  functions: Beginning execution of "onCreateSubComment"
>  {"severity":"INFO","message":"Error: 5 NOT_FOUND: no entity to update:
app: \"dev~muraita-main\"\npath <\n  Element {\n    type: \"posts\"\n
 name: \"{postId}\"\n  }\n  Element {\n    type: \"comments\"\n    name:
\"2022-09-01T12:55:24.748743\"\n  }\n>\n\n    at Object.callErrorFromStatus
***@***.***/grpc-js/build/src/call.js:31:19)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client.js:190:52)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:365:141)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:328:181)\n
   at
***@***.***/grpc-js/build/src/call-stream.js:188:78\n
   at processTicksAndRejections
(node:internal/process/task_queues:78:11)\nfor call at\n    at
ServiceClientImpl.makeUnaryRequest
***@***.***/grpc-js/build/src/client.js:160:30)\n
   at ServiceClientImpl.<anonymous>
***@***.***/grpc-js/build/src/make-client.js:105:19)\n
   at
***@***.***/firestore/build/src/v1/firestore_client.js:205:29\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16\n
   at repeat
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:118:13\n
   at OngoingCallPromise.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/call.js:67:27)\n
   at NormalApiCaller.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/createApiCall.js:81:30\n
   at processTicksAndRejections
(node:internal/process/task_queues:96:5)\nCaused by: Error\n    at
WriteBatch.commit
***@***.***/firestore/build/src/write-batch.js:417:23)\n
   at DocumentReference.update
***@***.***/firestore/build/src/reference.js:393:14)\n
   at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/lib/index.js:57:14\n
   at cloudFunction
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/firebase-functions/lib/cloud-functions.js:78:23)\n
   at
/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:578:16\n
   at runFunction
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:565:15)\n
   at runBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:577:11)\n
   at processBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:560:11)\n
   at invokeTrigger
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:641:19)\n
   at handleMessage
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:735:15)
{\n  code: 5,\n  details: 'no entity to update: app:
\"dev~muraita-main\"\\n' +\n    'path <\\n' +\n    '  Element {\\n' +\n
 '    type: \"posts\"\\n' +\n    '    name: \"{postId}\"\\n' +\n    '
 }\\n' +\n    '  Element {\\n' +\n    '    type: \"comments\"\\n' +\n    '
   name: \"2022-09-01T12:55:24.748743\"\\n' +\n    '  }\\n' +\n
 '>\\n',\n  metadata: Metadata {\n    internalRepr: Map(1) { 'content-type'
=> [Array] },\n    options: {}\n  },\n  note: 'Exception occurred in retry
method that was not classified as transient'\n}"}
⚠  functions: Error: 5 NOT_FOUND: no entity to update: app:
"dev~muraita-main"
path <
  Element {
    type: "posts"
    name: "{postId}"
  }
  Element {
    type: "comments"
    name: "2022-09-01T12:55:24.748743"
  }
>

    at Object.callErrorFromStatus
***@***.***/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:328:181)
    at
***@***.***/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest
***@***.***/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.<anonymous>
***@***.***/grpc-js/build/src/make-client.js:105:19)
    at
***@***.***/firestore/build/src/v1/firestore_client.js:205:29
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCallPromise.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/google-gax/build/src/createApiCall.js:81:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Caused by: Error
    at WriteBatch.commit
***@***.***/firestore/build/src/write-batch.js:417:23)
    at DocumentReference.update
***@***.***/firestore/build/src/reference.js:393:14)
    at
/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/lib/index.js:57:14
    at cloudFunction
(/Users/jober/AndroidStudioProjects/mainProject/muraita_main/server/functions/node_modules/firebase-functions/lib/cloud-functions.js:78:23)
    at
/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:578:16
    at runFunction
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:565:15)
    at runBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:577:11)
    at processBackground
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:560:11)
    at invokeTrigger
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:641:19)
    at handleMessage
(/opt/homebrew/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:735:15)
⚠  Your function was killed because it raised an unhandled error.




on the onUserCreate, there is no error when it is being invoked, but the
problem is it is not updating the auth displayName, which i also dont have
any idea why..

once i got these all right, then the next stuff is now easy because i
already have a guide.

I would really appreciate it if you could help me out with these..Thank you.

**Comment by yuchenshi** [comment]
@johnberang12 Please kindly go to the GitHub issue linked ( https://github.com/firebase/firebase-tools-ui/issues/847 ) and upload video and screenshots on GitHub web. GitHub does not parse *email attachments*.

This repo is dedicated to the Firebase Emulator UI open source project and is not a general support forum. For questions about Firebase, please post on StackOverflow or reach out to Firebase Support.

**Comment by johnberang12** [comment]
i understood..i solved it though.

**Comment by johnberang12** [comment]
![302203246_444602121060478_5504999427854186581_n](https://user-images.githubusercontent.com/84907373/188249326-6a789e65-37ce-4a06-b324-5b7c1e56db92.jpg)
![302118922_1089313525090522_4684784432570467_n](https://user-images.githubusercontent.com/84907373/188249351-4918ae3e-fc25-49dc-b99e-a124297e4c17.jpg)
![302038410_794868091653619_7843411304772238599_n](https://user-images.githubusercontent.com/84907373/188249362-7053c310-2ec0-43d4-9a1d-cb588351168c.jpg)

https://user-images.githubusercontent.com/84907373/188249368-c47dd048-4e16-4a7b-bf35-0ab7c4886a68.mp4

**Comment by johnberang12** [comment]
im closing this cos it seems the issue is fixed..i opened the emulator this morning and i now can see the sub collection without manually creating it.
