### ISSUE TITLE
Storage Emulator preview when clicking on file shows blank screen

### ISSUE THREAD

**Issue by tonyjhuang** [firebase/firebase-tools-ui#862]
**Describe the bug**
Initially reported in firebase/firebase-tools repo: https://github.com/firebase/firebase-tools/issues/4915

Clicking on a file with an image content-type in the file browser shows a blank white screen. Clicking on any other file shows the metadata preview UI as expected.

**To Reproduce**

1. Open the Emulator UI
2. Click on `Upload File` and choose a file named `<anything>.png`
3. Click on the new entry in the file browser for `<anything>.png`
4. Observe white screen

**Expected behavior**
Metadata preview UI displays

**Screenshots**
Example of broken files: 

![image](https://user-images.githubusercontent.com/1237337/194357487-55dfeb51-257f-4bbf-a476-0bfc8230da9d.png)

Example of correct UI for "application/octet-stream" content type:

![image](https://user-images.githubusercontent.com/1237337/194357154-fd172148-3bf7-434b-abf4-7766327774a2.png)

**Comment by christhompsongoogle** [comment]
I'm not able to repro on the latest version (Mac). From some previous PRs I see that the preview URL logic was recently (Aug 10) changed in https://github.com/firebase/firebase-tools-ui/pull/848, though it's not clear why. I'm not able to repro on previous versions either - so it may still be an issue on some platforms/browsers.

@tjlav5 Can you add some detail on what motivated the above change?

**Comment by christhompsongoogle** [comment]
Yes we've released a few version recently (mostly related to connectivity) but it must have included the fix I linked above. Thanks for checking Tony !
