### ISSUE TITLE
"Please update your Firestore Emulator" on Firestore/Requests with v11.14.0

### ISSUE THREAD

**Issue by 2i2i** [firebase/firebase-tools-ui#863]
Note: Before filing bugs in this repo, please ensure that this is a bug for the Emulator Suite UI. Emulator Suite and/or Firebase CLI bugs should be filed under the firebase-tools repo here:
https://github.com/firebase/firebase-tools/issues/new/choose

**Describe the bug**
http://localhost:4000/firestore/requests shows "Please update your Firestore Emulator" even though i am on the newest version ~ there is data available

**To Reproduce**
`firebase emulators:start` with firestore running

**Expected behavior**
log of firestore

**Screenshots**
https://imgur.com/a/0B2CmnR

**Desktop (please complete the following information):**

- OS: newest macOS
- Browser newest chrome
- on m1 macbook air

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yuchenshi** [comment]
Fixed in CLI v11.14.1. Thanks everyone for the help!
