### ISSUE TITLE
Hosting: Geting 404 error page instead of index.html

### ISSUE THREAD

**Issue by ASHHAD-BASE** [firebase/firebase-tools-ui#866]
I have recently updated firebase tools by `npm update -g firebase-tools` 
and the expected hosting emulator behavior has changed.
I am getting 404 page instead of index.html. 

**Expected behavior**

when accessing `localhost:5000` I should get `localhost:5000/index.html`
but i am getting `404` not found page 
also I am getting`localhost:5000/index.html` when using url `localhost:5000/index.html`.

**To Reproduce**

I have tried installing emulator suite from scratch on another machine 
and still getting 404 not found page instead of index.html
so this bug may have been introduced in new versions of  firebase-tools

- OS: windows
- Browser :n/a
- firebase-tools Version :11.14.4

**Comment by jhuleatt** [comment]
Hi @ASHHAD-BASE, I see you also filed this at https://github.com/firebase/firebase-tools/issues/5133, which is the right spot for this issue. I'm going to close this, please follow the firebase-tools issue for updates.
