### ISSUE TITLE
Filter popup in firestore emulators not showing

### ISSUE THREAD

**Issue by stefandim91** [firebase/firebase-tools-ui#919]
**Describe the bug**
Firestore emulators filter pop doesn't show up when clicked.

**To Reproduce**

1. Run firestore emulator
2. Click on filter icon
4. Only partial of the popup is visible

**Expected behavior**
The popup for filters should be visible on top of other elements

**Screenshots**
![chrome_RwMkz2WR6b](https://user-images.githubusercontent.com/64243042/218101828-c7683d74-2499-4371-bd24-5ac24a0ff716.gif)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome/Firefox
- Version: 110/109

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**
`"firebase-tools": "^11.22.0",`

**Comment by lisbuenas** [comment]
+1

**Comment by timurcatakli** [comment]
+1

**Comment by TravisSperry** [comment]
Has anyone found a workaround for this one? I tried to dig in a little, but didn't have any luck

**Comment by stefandim91** [comment]
Open the elements tab and fin this div:
![image](https://user-images.githubusercontent.com/64243042/219132207-78553e05-0dca-45f8-8dbe-b71eb3f1226c.png)

Add position fixed to style:
![image](https://user-images.githubusercontent.com/64243042/219132367-dc6a9035-b82e-44cd-9450-29a1cc08901a.png)

It appears at the top left corner:
![image](https://user-images.githubusercontent.com/64243042/219132646-42990d75-1afd-4147-a48f-93e899364895.png)

It's supper annoying tbh, but didn't find any other way to use it otherwise.

**Comment by TravisSperry** [comment]
Ahhh good call. Thanks. I just downgraded `firebase-tools` to 11.19.0

**Comment by christhompsongoogle** [comment]
Resolved in https://github.com/firebase/firebase-tools-ui/pull/908
