### ISSUE TITLE
Emulator UI has exited with code: 1

### ISSUE THREAD

**Issue by arturosanz** [firebase/firebase-tools-ui#939]
**Describe the bug**

The Emulator UI can't start.

**To Reproduce**

Follow the steps of the [Local Development with the Firebase Emulator Suite](https://firebase.google.com/codelabs/firebase-emulator#0) codelab. Running the emulators with `$ firebase emulators:start --import=./seed` on step 3 fails because of the UI emulator. The rest seem to work fine.

**Expected behavior**

```
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
└─────────────────────────────────────────────────────────────┘

┌────────────────┬────────────────┐
│ Emulator       │ Host:Port      │
├────────────────┼────────────────┤
│ Authentication │ 127.0.0.1:9099 │
├────────────────┼────────────────┤
│ Functions      │ 127.0.0.1:5001 │
├────────────────┼────────────────┤
│ Firestore      │ 127.0.0.1:8080 │
├────────────────┼────────────────┤
│ Hosting        │ 127.0.0.1:5000 │
└────────────────┴────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500, 9150
```

**Screenshots**

```
❯ firebase emulators:start --import=./seed
i  emulators: Starting emulators: auth, functions, firestore, hosting
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, pubsub, storage
i  firestore: Importing data from /$MY_LOCAL_PATH/emulators-codelab/codelab-initial-state/seed/firestore_export/firestore_export.overall_export_metadata
i  firestore: Firestore Emulator logging to firestore-debug.log
✔  firestore: Firestore Emulator UI websocket is running on 9150.
i  hosting[$MY_PROJECT_ID]: Serving hosting files from: public
✔  hosting[$MY_PROJECT_ID]: Local server: http://127.0.0.1:5000
i  ui: Emulator UI logging to ui-debug.log
⚠  ui: Fatal error occurred:
   Emulator UI has exited with code: 1,
   stopping all running emulators
i  ui: Stopping Emulator UI
⚠  ui: Error stopping Emulator UI
i  functions: Stopping Functions Emulator
i  hosting: Stopping Hosting Emulator
i  firestore: Stopping Firestore Emulator
i  auth: Stopping Authentication Emulator
i  eventarc: Stopping Eventarc Emulator
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator
```

[ui-debug.log](https://github.com/firebase/firebase-tools-ui/files/11219872/ui-debug.log)

**Desktop (please complete the following information):**

- node v16.20.0
- npm 8.19.4
- firebase CLI 11.26.0
- OS: MacOS Monterey 12.6.3
- Browser: Brave
- Version: 1.49.120 Chromium: 111.0.5563.64

**Additional context**

I was able to temporarily "ignore" the problem by adding `"ui": { "enabled": false }` to the `firebase.json` file.

**Comment by y-takebe** [comment]
I am experiencing the same phenomenon.

I am getting the same error in ui-debug.log. I tried to fix that directly! But only to get another error next.

* node v18.16.0
* pnpm 8.2.0
* firebase CLI 11.27.0
* OS: MacOS Ventura 13.2.1

> I was able to temporarily "ignore" the problem by adding "ui": { "enabled": false } to the firebase.json file.

Thanks for the great workaround!

**Comment by BoveFabio** [comment]
I have noticed that for me it's downloading Version 1.11.5 into `~/.cache/firebase/emulators`. That version seems to contain a corrupted file as my `ui-debug.log` says 
```
SyntaxError: Unexpected string
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```
`~/.cache/firebase/emulators/ui-v1.11.5/server/server.js:569` : `re"use strict";`

Comparing that to the v 1.11.4 on a colleague's machine there's a `return` statement in that place. So it seems to me that v1.11.5 of the UI emulator is simply broken because of corruption.

What's surprising me: Both my colleague and I have v 11.27.0 of `firebase-tools` installed but on my machine it downloads v1.11.5 and on his machine it downloads v1.11.4. That is the case even when I delete my v1.11.5 files from and copy his v1.11.4 files into my `~/.cache/firebase/emulators`.

I hope that information helps.

**Comment by iluvsoup** [comment]
Experiencing this issue as well, guess we'll just wait for the PR to merge?

**Comment by bushblade** [comment]
I am also experiencing the same issue.

**Comment by bushblade** [comment]
I am also experiencing the same issue.

Node - 19.8.1
OS - Manjaro Linux
Firebase cli - 11.28.0
Emulators UI v1.11.5

I can't locate my ui-debug.log anywhere on my system though, where should that be?
Tried from home directory and project directory both
```sh
fd ui-log
```
And 
```sh
fd --hidden ui-log
```
But there is no output.

**Comment by christhompsongoogle** [comment]
The fix for this was released in v11.30.0, see here: https://github.com/firebase/firebase-tools/releases/tag/v11.30.0

Please upgrade past this to resolve the issue and let me know if you're still encountering any issues.

**Comment by sathishvj** [comment]
@BoveFabio How do you download a specific version of the emulator? I'm still having this issue with node v20.5.1 and firebase v12.5.2.

**Comment by danielbraghini** [comment]
I had an old version of firebase-tools in my package.json and a newer version globally.
So I removed firebase-tools from package.json and kept it globally and it worked.
It also works by updating firebase-tools in package.json.

**Comment by AbhijithBn** [comment]
> @BoveFabio How do you download a specific version of the emulator? I'm still having this issue with node v20.5.1 and firebase v12.5.2.

This is just a suggestion. You can install firebase-cli using brew. That fixed this issue for me.

**Comment by kuChayatorn** [comment]
install firebase-cli using Brew also solves my issues. but I don't know exactly what going on and why installed using npm gives the error.
   ui: Fatal error occurred:
   Emulator UI has exited with code: 1,
   stopping all running emulators
   
   firebase 13.10.1
   npm 10.5.2
   node v20.13.1
   Homebrew 4.3.2

**Comment by talesmgodois** [comment]
> > @BoveFabio How do you download a specific version of the emulator? I'm still having this issue with node v20.5.1 and firebase v12.5.2.
> 
> This is just a suggestion. You can install firebase-cli using brew. That fixed this issue for me.

Well, Uninstalling the version I have instlaeed using curl, and then installing using `npm i -g firebase-tools` worked as well,

**Comment by MiguelG97** [comment]
Same for me, uninstalling the curl installation and using `brew install firebase-cli `instead worked fine

**Comment by Applicafroguy** [comment]
> > > @BoveFabio How do you download a specific version of the emulator? I'm still having this issue with node v20.5.1 and firebase v12.5.2.
> > 
> > 
> > This is just a suggestion. You can install firebase-cli using brew. That fixed this issue for me.
> 
> Well, Uninstalling the version I have instlaeed using curl, and then installing using `npm i -g firebase-tools` worked as well,

Curl installation was the issue for me this `npm i -g firebase-tools`  solved it

**Comment by SakhileMamba** [comment]
uninstall and reinstall firebase tools

**Comment by babakoto** [comment]
Remove firebase 
`sudo rm -r /usr/local/bin/firebase `

Install with brew
`brew install firebase-cli`

**Comment by matheusbaumgart** [comment]
For me it was in the wrong node version.
