### ISSUE TITLE
can't lauch emulators cos UI exit with code 1

### ISSUE THREAD

**Issue by wildergd** [firebase/firebase-tools-ui#940]
**Describe the bug**
I have switched to a mac with chip Apple M2 Pro and now i can't start emulators cos UI exit with code 1... i have tried several solutions: downgrading, using a lower version of node... i have tried node18, node16, node14 and nothing have worked... the only solution was to disable UI... but i need UI.... 

**Screenshots**
<img width="655" alt="image" src="https://user-images.githubusercontent.com/3240995/232375970-bd56a821-0301-473f-8dc5-a8324aa5330c.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/3240995/232376015-b99b684b-23aa-489d-a167-4e37d4617390.png">

- OS: MacOS 13.3.1
- Device: Macbook Pro 2023 14"

**Comment by lovpankaj** [comment]
Happening On Windows too

**Comment by lovpankaj** [comment]
Manually unzipping the ui zip file at the same location fixed the issue

**Comment by wildergd** [comment]
thanks... it worked like a charm....

**Comment by liquidx** [comment]
Same thing is happening to me on MacBook Pro M2 2023. I've also tried different node versions, etc. Using node v18.16.0.

Unzipping it manually also fixed it for me, so maybe it's something happening with the original downloading and unpacking of the zip file in node?

**Comment by lovpankaj** [comment]
Clearly there is some issue with the unzipping the file. Firebase team can you please look into this?

**Comment by mZaidSk** [comment]
My node version 18.16.0, firebase v 11.29.1 is experiencing the same problem.
The problem was solved by unzipping the file.

**Comment by christhompsongoogle** [comment]
The fix for this was released in v11.30.0, see here: https://github.com/firebase/firebase-tools/releases/tag/v11.30.0

Please upgrade past this to resolve the issue and let me know if you're still encountering any issues.
